const colors = {
    green: {
        id: 1,
        name: 'vert',
        color: 'bg-green-700',
        title: 'text-green-700',
        bg: 'bg-green-100',
        filter: 'border-green-200 hover:bg-green-100',
    },
    blue: {
        id: 2,
        name: 'bleue',
        color: 'bg-blue-700',
        title: 'text-blue-700',
        bg: 'bg-blue-100',
        filter: 'border-blue-200 hover:bg-blue-100',
    },
    red: {
        id: 3,
        name: 'rouge',
        color: 'bg-red-700',
        title: 'text-red-700',
        bg: 'bg-red-100',
        filter: 'border-red-200 hover:bg-red-100',
    },
    orange: {
        id: 4,
        name: 'orange',
        color: 'bg-orange-700',
        title: 'text-orange-700',
        bg: 'bg-orange-100',
        filter: 'border-orange-200 hover:bg-orange-100',
    },
    gray: {
        id: 5,
        name: 'gray',
        color: 'bg-gray-700',
        title: 'text-gray-700',
        bg: 'bg-gray-100',
        filter: 'border-gray-200 hover:bg-gray-100',
    },
    amber: {
        id: 6,
        name: 'ambre',
        color: 'bg-amber-700',
        title: 'text-amber-700',
        bg: 'bg-amber-100',
        filter: 'border-amber-200 hover:bg-amber-100',
    },
    yellow: {
        id: 7,
        name: 'yellow',
        color: 'bg-yellow-700',
        title: 'text-yellow-700',
        bg: 'bg-yellow-100',
        filter: 'border-yellow-200 hover:bg-yellow-100',
    },
    lime: {
        id: 8,
        name: 'citron',
        color: 'bg-lime-700',
        title: 'text-lime-700',
        bg: 'bg-lime-100',
        filter: 'border-lime-200 hover:bg-lime-100',
    },
    cyan: {
        id: 9,
        name: 'cyan',
        color: 'bg-cyan-700',
        title: 'text-cyan-700',
        bg: 'bg-cyan-100',
        filter: 'border-cyan-200 hover:bg-cyan-100',
    },
    violet: {
        id: 10,
        name: 'violet',
        color: 'bg-violet-700',
        title: 'text-violet-700',
        bg: 'bg-violet-100',
        filter: 'border-violet-200 hover:bg-violet-100',
    },
    fuchsia: {
        id: 11,
        name: 'fuchsia',
        color: 'bg-fuchsia-700',
        title: 'text-fuchsia-700',
        bg: 'bg-fuchsia-100',
        filter: 'border-fuchsia-200 hover:bg-fuchsia-100',
    },
    rose: {
        id: 12,
        name: 'rose',
        color: 'bg-rose-700',
        title: 'text-rose-700',
        bg: 'bg-rose-100',
        filter: 'border-rose-200 hover:bg-rose-100',
    },
}

export default colors;
